* Axiomatic Set Theory as the Foundation of a Computer Science Education

This repository contains a hypertext document viewable on the Web at http://calcnerd256.dyndns.org:15211/hat/unsorted/setTheory/

** Topics
*** logic
**** truth tables
***** NAND
A universal operator.
We'll briefly mention its relationship with transistors.
***** all binary boolean operators
There are only 16 of them.
We evaluate them Wolfram-style.
They form a group.
Maybe we'll make an interactive page to experiment with these.
We'll construct each with NANDs.
*** teaser on set operations
very high-level, but contains "deep" hyperlinks
*** proofs
**** What is an axiom, and why should I care?
What happens if we try to construct math some other way?
*** ZFC
building upon previous teaser,
quickly goes deep into ways set theory can be counter-intuitive

** Traversal
This document is going to be hypertextual.
*** Essential
Some hyperlinks will lead to necessary prerequisites.
Failure to traverse these links will leave the reader unable to proceed.
*** Supplemental
Some hyperlinks will lead down a rabbit-hole to unnecessary details.
It is the author's hope that these topics will be of interest to the more adventurous reader.
However, these links can be distracting and should be avoided on the first pass.
They will be a different color.
The terminology for these is "deep" links.

** TODO
*** plan out a lesson plan that goes from knowing nothing about actual math to fluency in Set Theory
*** render the lesson plan as hypertext
*** attempt to teach from this lesson plan
*** collect feedback and iterate

** Tactics
Should I try the Socratic Method?
Under what conditions would that be a good idea?

* LibTransclusion
I want to be able to transclude other documents inline.
I think I'll write a JS library for it.
** Inline Transclusion
** API
An element with a class of "external" gets replaced.
The replacement is done by looking up the document at a URL.
The URL comes from the element's "data-href" attribute.
Elements of class "snippet" in the transcluded document replace the "external"-classed element.
** TODO
*** Implement the API designed so far
*** Design a better API as a superset of the current one
*** Implement the new design
